FROM openjdk:12-jdk

RUN yum install -y oracle-nodejs-release-el7 oracle-release-el7
RUN yum install -y nodejs
RUN yum install -y procps-ng coreutils net-tools nmap vim iputils

ARG app_jar=rest-@{project.version}.jar

COPY rest-@{project.version}.jar /

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/rest-@{project.version}.jar"]
