export const LOAD_ALL_TOPICS_SUCCESS = 'LOAD_ALL_TOPICS_SUCCESS';
export const LOAD_ALL_TOPICS_FAILURE = 'LOAD_ALL_TOPICS_FAILURE';
export const LOAD_ALL_TOPICS_STARTED = 'LOAD_ALL_TOPICS_STARTED';

export const SELECT_TOPIC = 'SELECT_TOPIC';
export const SELECT_PARITITON = 'SELECT_PARTITION';

export const LOAD_ALL_BROKERS_SUCCESS = 'LOAD_ALL_BROKERS_SUCCESS';
export const LOAD_ALL_BROKERS_FAILURE = 'LOAD_ALL_BROKERS_FAILURE';
export const LOAD_ALL_BROKERS_STARTED = 'LOAD_ALL_BROKERS_STARTED';

export const LOAD_TOPIC_MESSAGES_SUCCESS = 'LOAD_TOPIC_MESSAGES_SUCCESS';
export const LOAD_TOPIC_MESSAGES_FAILURE = 'LOAD_TOPIC_MESSAGES_FAILURE';
export const LOAD_TOPIC_MESSAGES_STARTED = 'LOAD_TOPIC_MESSAGES_STARTED';

export const LOAD_TOPIC_CONSUMERS_SUCCESS = 'LOAD_TOPIC_CONSUMERS_SUCCESS';
export const LOAD_TOPIC_CONSUMERS_FAILURE = 'LOAD_TOPIC_CONSUMERS_FAILURE';
export const LOAD_TOPIC_CONSUMERS_STARTED = 'LOAD_TOPIC_CONSUMERS_STARTED';